<a href="https://colab.research.google.com/github/kunalbathija/Udemy-TF-2.0/blob/master/Basic_Computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [10]:
a = tf.constant(3.0)
b = tf.constant(4.0)
c = tf.sqrt(a**2+b**2)

print("c:",c)
print(f"c: {c}")

c: tf.Tensor(5.0, shape=(), dtype=float32)
c: 5.0


In [12]:
c.numpy()

5.0

In [13]:
type(c.numpy())

numpy.float32

In [17]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.tensordot(a,b,axes=[0,0])
print(f"c: {c}")

c: 32


In [19]:
a.numpy().dot(b.numpy())

32

In [26]:
import numpy as np
A0 = np.random.rand(3,3)
B0 = np.random.rand(3,1)
C0 = A0.dot(B0)
print(f"C0: {C0}")

C0: [[1.53252794]
 [1.20414625]
 [1.28969141]]


In [28]:
#In Tensorflow
A = tf.constant(A0)
B = tf.constant(B0)
C = tf.matmul(A, B)
C

<tf.Tensor: shape=(3, 1), dtype=float64, numpy=
array([[1.53252794],
       [1.20414625],
       [1.28969141]])>

In [30]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant(1)
c = a+b
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [33]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,3],[4,5]])
c = a * b
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]], dtype=int32)>