<a href="https://colab.research.google.com/github/kunalbathija/Udemy-TF-2.0/blob/master/RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.2.0-rc4


In [0]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
# Things I should automatically know and have to memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [4]:
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)
X

array([[[ 1.721396  ,  0.85878981, -1.10917103],
        [-0.92029393,  0.69354756, -0.62539677],
        [ 1.3745834 ,  1.51678308, -1.14312419],
        [ 0.63301751, -0.40852696,  0.18539497],
        [ 0.64163882,  0.61505922,  1.9693778 ],
        [ 0.43262314,  1.89389283,  0.94158159],
        [-0.22466866,  1.5512478 , -0.27415068],
        [-0.10173867,  0.75510099,  0.4955274 ],
        [ 0.19047418, -0.06694285, -0.30011354],
        [-0.85117448,  0.30719048, -1.23439841]]])

In [0]:
# Make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [6]:
Yhat = model.predict(X)
print(Yhat) 

[[0.40158632 0.01879556]]


In [7]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.layers[1].get_weights()

[array([[-0.03456748,  0.19545668, -0.6483735 , -0.18024558, -0.2957186 ],
        [ 0.17131096,  0.26219386, -0.5454117 , -0.41868323,  0.5392216 ],
        [ 0.10676634,  0.81628126, -0.78813833, -0.21814907,  0.08882868]],
       dtype=float32),
 array([[-0.21434021,  0.6351548 ,  0.16754277,  0.6262518 , -0.3610746 ],
        [ 0.26489344,  0.6556784 , -0.3447431 , -0.58887756, -0.18518306],
        [-0.8637115 , -0.07824354,  0.02575315, -0.39628482, -0.30029243],
        [ 0.3685699 , -0.31554767,  0.29825574, -0.10374059, -0.815394  ],
        [ 0.04526002,  0.24692498,  0.8737631 , -0.30533287,  0.28335398]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [11]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [0]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [13]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[0.40158625 0.01879553]
